### PR TITLE
Add typings for Typescript compilation

### PR DESCRIPTION
**Pull request by adrienverge**
Add typings to the package, so Typescript programs can directly import this library as a module and use it with:

```ts
import {code as dragAndDrop} from 'html-dnd';

driver.executeScript(dragAndDrop, draggable, droppable);
```

Also update docs accordingly.

### CODE REVIEW

**Comment by adrienverge** [comment]
Hi @Kuniwak, have you had a chance to take a look?

**Comment by Kuniwak** [comment]
Sorry for my late reply :bowing_man: 

After test pass, I'm gonna merge it.
Thanks!

**Review by Kuniwak — APPROVED** [review]
:+1:

**Comment by Kuniwak** [comment]
Thanks a lot! :pray:

**Comment by adrienverge** [comment]
Thank you!

Now what would be very nice is a new release on npm ;)

**Comment by Kuniwak** [comment]
I shipped the [minor release](https://github.com/Kuniwak/html-dnd/releases/tag/v1.2.0) for this patch.

**Comment by adrienverge** [comment]
Great!

**Pull request merged**
